-- Day 10：建立项目、工具和标签的 PostgreSQL 数据结构。
create table public.projects (
  id text primary key,
  slug text not null unique,
  name text not null,
  description text not null,
  long_description text not null,
  status text not null check (status in ('building', 'completed', 'paused')),
  cover_image text,
  project_url text,
  github_url text,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.project_highlights (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  content text not null,
  sort_order integer not null default 0 check (sort_order >= 0)
);

create table public.tools (
  id text primary key,
  name text not null,
  description text not null,
  url text not null unique,
  category text not null check (category in ('AI', '开发', '学习', '效率')),
  is_favorite boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tags (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table public.project_tags (
  project_id text not null references public.projects(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (project_id, tag_id)
);

create table public.tool_tags (
  tool_id text not null references public.tools(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (tool_id, tag_id)
);

-- 为常用筛选、排序和反向关联查询建立索引。
create index projects_status_idx on public.projects(status);
create index project_highlights_order_idx on public.project_highlights(project_id, sort_order);
create index project_tags_tag_id_idx on public.project_tags(tag_id);
create index tools_category_idx on public.tools(category);
create index tools_favorite_idx on public.tools(is_favorite);
create index tool_tags_tag_id_idx on public.tool_tags(tag_id);

-- 由数据库统一维护更新时间，避免每个调用方重复实现。
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger projects_set_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

create trigger tools_set_updated_at
before update on public.tools
for each row execute function public.set_updated_at();

-- 所有公开表默认拒绝访问，再通过策略只开放读取。
alter table public.projects enable row level security;
alter table public.project_highlights enable row level security;
alter table public.tools enable row level security;
alter table public.tags enable row level security;
alter table public.project_tags enable row level security;
alter table public.tool_tags enable row level security;

create policy "Public can read projects" on public.projects
for select to anon, authenticated using (true);
create policy "Public can read project highlights" on public.project_highlights
for select to anon, authenticated using (true);
create policy "Public can read tools" on public.tools
for select to anon, authenticated using (true);
create policy "Public can read tags" on public.tags
for select to anon, authenticated using (true);
create policy "Public can read project tags" on public.project_tags
for select to anon, authenticated using (true);
create policy "Public can read tool tags" on public.tool_tags
for select to anon, authenticated using (true);
