-- 将工具分类提升为独立数据，后台可以完整管理分类。
create table public.tool_categories (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(btrim(name)) between 1 and 40),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 先收纳现有工具分类，迁移不会丢失或改写已有工具。
insert into public.tool_categories (name)
select distinct btrim(category)
from public.tools
order by 1;

alter table public.tools
  add constraint tools_category_fkey
  foreign key (category) references public.tool_categories(name)
  on update cascade
  on delete restrict;

create trigger tool_categories_set_updated_at
before update on public.tool_categories
for each row execute function public.set_updated_at();

alter table public.tool_categories enable row level security;
revoke all privileges on table public.tool_categories from anon, authenticated;
grant select, insert, update, delete on public.tool_categories to authenticated;
grant usage, select on sequence public.tool_categories_id_seq to authenticated;

create policy "Admin reads tool categories" on public.tool_categories
for select to authenticated
using ((select auth.uid()) = 'e640aac4-933c-4c59-b28b-12ec7561bceb'::uuid);

create policy "Admin inserts tool categories" on public.tool_categories
for insert to authenticated
with check ((select auth.uid()) = 'e640aac4-933c-4c59-b28b-12ec7561bceb'::uuid);

create policy "Admin updates tool categories" on public.tool_categories
for update to authenticated
using ((select auth.uid()) = 'e640aac4-933c-4c59-b28b-12ec7561bceb'::uuid)
with check ((select auth.uid()) = 'e640aac4-933c-4c59-b28b-12ec7561bceb'::uuid);

create policy "Admin deletes tool categories" on public.tool_categories
for delete to authenticated
using ((select auth.uid()) = 'e640aac4-933c-4c59-b28b-12ec7561bceb'::uuid);
